### ISSUE TITLE
How to generate a pickle file of a animation sequence？

### ISSUE THREAD

**Issue by ch1998** [SamsungLabs/DINAR#1]
Outstanding paper! May I ask how I will replace the animation sequence, how should I generate a new animation sequence file？

**Comment by david-svitov** [comment]
Hi! You can use animation sequences from the AMASS Dataset: https://amass.is.tue.mpg.de/
They have SMPL-X animated with motion capture. But you have to reorder the file structure so it matches the current animation sequence. You can do it with python, just make sure the dicts are in the same format.

**Comment by ch1998** [comment]
> Hi! You can use animation sequences from the AMASS Dataset: https://amass.is.tue.mpg.de/ They have SMPL-X animated with motion capture. But you have to reorder the file structure so it matches the current animation sequence. You can do it with python, just make sure the dicts are in the same format.

Thanks for your reply, I will try it

**Comment by ch1998** [comment]
Thanks for your reply, I will try it！

**Comment by ch1998** [comment]
Hi! I tried to use the model to export the SPML-X params of the person from a picture, but the dimension of the data is not the same as the dimension given in your code. How do you deal with the dimension?
yours dim：                                                            my dim：
global_orient  :  (1, 3)                                             global_orient  :  (1, 3, 3)
body_pose  :  (1, 63)                                               body_pose  :  (21, 3, 3)
left_hand_pose  :  (1, 12)                                        left_hand_pose  :  (15, 3, 3)
right_hand_pose  :  (1, 12)                                      right_hand_pose  :  (15, 3, 3)
jaw_pose  :  (1, 3)                                                    jaw_pose  :  (1, 3, 3)
leye_pose  :  (1, 3)                                                  null
reye_pose  :  (1, 3)                                                  null
betas  :  (1, 10)                                                       betas  :  (10,)
expression  :  (1, 10)                                               expression  :  (10,)

I use expose to get the params.

**Comment by david-svitov** [comment]
@ch1998 Yes, it is camera parameters. But as you can see in video_maker.py we don't really use them, so it shouldn't be a big problem.
