### ISSUE TITLE
Error in building the docker file

### ISSUE THREAD

**Issue by AshokBatakala** [SamsungLabs/DINAR#2]
Great paper guys! i am trying to run the code. It's throwing an error while building the docker Image. in this line
```
RUN pip install git+https://github.com/rmbashirov/minimal_pytorch_rasterizer   
```
specifically, the error is with `#0 20.39   Building wheel for minimal-pytorch-rasterizer (setup.py): finished with status 'error'` . 

How to fix these? did i forget anything.

**Comment by david-svitov** [comment]
Hard to say from here) You can send me your whole logs so I can give you a more accurate response.
But it looks like an issue with the Docker version. Try commenting out this line in the Dockerfile:
`ENV PATH=/home/$USERNAME/miniconda/envs/gent_docker/bin:$PATH`

**Comment by AshokBatakala** [comment]
docker version is `Docker version 24.0.2, build cb74dfc`.  
these are the logs when running `sudo bash docker/build.sh`.  
[Normal.txt](https://github.com/SamsungLabs/DINAR/files/1194887  

### when line 93 is commented out  
it caused someother error.
[comment_line_93.txt](https://github.com/SamsungLabs/DINAR/files/11948883/comment_line_93.txt)
6/Normal.txt)  

### when line 105 is commented out 
`RUN pip install git+https://github.com/rmbashirov/minimal_pytorch_rasterizer`
[comment_line_105.txt](https://github.com/SamsungLabs/DINAR/files/11948892/comment_line_105.txt)

_which docker version did you use? Let me know, I'll try with it._

**Comment by david-svitov** [comment]
I reproduced this error on one of our servers. But I have no idea why we face this issue - the version of Docker is the same.
The easiest fix is to not install `minimal_pytorch_rasterizer` with the Docker file and install it later with:
`pip install git+https://github.com/rmbashirov/minimal_pytorch_rasterizer` 
from inside the container

**Comment by AshokBatakala** [comment]
Thanks,
I tried that. but, it is asking for password when I run `sudo` commands. from the docker file it seems that it shouldn't ask any password. right?

I am new to these.

**Comment by david-svitov** [comment]
I guess `pip` should work without `sudo`. Did you try to use `pip` without `sudo`?

**Comment by AshokBatakala** [comment]
Not `pip`. other commands

**Comment by david-svitov** [comment]
Ok, I'll try to fix this file tomorrow. In the meantime, you can try to comment out this whole part:
```
RUN wget https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-linux.zip
RUN sudo unzip ninja-linux.zip -d /usr/local/bin/
RUN sudo update-alternatives --install /usr/bin/ninja ninja /usr/local/bin/ninja 1 --force 


ARG ssh_prv_key
ARG ssh_pub_key
RUN mkdir ~/.ssh/
RUN echo "$ssh_prv_key" > ~/.ssh/id_rsa && \
    echo "$ssh_pub_key" > ~/.ssh/id_rsa.pub && \
    echo "StrictHostKeyChecking no" > ~/.ssh/config && \
    chmod 600 ~/.ssh/id_rsa && \
    chmod 600 ~/.ssh/id_rsa.pub
```
It looks kind of useless for running inference code.

**Comment by david-svitov** [comment]
@AshokBatakala I have updated the Docker file and the installation guide in README.md.
